import{useState}from'react';import{Link}from'react-router-dom';import{naira}from'./api.js';import{Primary,Ghost}from'./App.jsx';
export const Img=({src,alt,className=''})=>{const[bad,setBad]=useState(false);return bad||!src?<div role="img" aria-label={alt} className={`bg-gradient-to-br from-blush/40 to-cream ${className}`}/>:<img src={src} alt={alt} loading="lazy" width="600" height="600" onError={()=>setBad(true)} className={className}/>};
export const Err=({msg,retry})=><div role="alert" className="rounded-2xl border border-line bg-white p-8 text-center"><p className="font-semibold">Something went wrong</p><p className="mt-1 text-sm text-mute">{msg}</p>{retry&&<button onClick={retry} className={Ghost+' mt-4'}>Try again</button>}</div>;
export const Skel=({n=4})=><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:n},(_,i)=><div key={i} className="aspect-[4/5] animate-pulse rounded-2xl bg-line"/>)}</div>;
export const ServiceCard=({s})=><article className="group overflow-hidden rounded-2xl border border-line bg-white transition hover:-translate-y-1 hover:shadow-lg">
 <div className="aspect-square overflow-hidden"><Img src={s.image} alt={`${s.name} nail set`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div>
 <div className="p-5"><h3 className="text-xl">{s.name}</h3><p className="mt-1 text-sm text-mute">{s.description}</p>
 <p className="mt-3 text-sm"><b className="text-rose">{s.priceLabel||naira(s.price)}</b> · {s.duration} min</p>
 <div className="mt-4 grid grid-cols-2 gap-2"><Link to={`/services/${s._id}`} className={Ghost}>View Details</Link><Link to={`/book?service=${s._id}`} className={Primary}>Book Now</Link></div></div></article>;
import{useEffect,useRef}from'react';import{motion,AnimatePresence}from'framer-motion';
let sub=()=>{};export const toast=(m,err)=>sub({m,err,id:Math.random()});
export function Toaster(){const[t,setT]=useState([]);useEffect(()=>{sub=x=>{setT(a=>[...a,x]);setTimeout(()=>setT(a=>a.filter(y=>y!==x)),3500)};return()=>{sub=()=>{}}},[]);
 return<div aria-live="polite" className="fixed bottom-24 left-1/2 z-[70] grid -translate-x-1/2 gap-2">{t.map(x=><div key={x.id} className={`rounded-full px-5 py-3 text-sm text-white shadow-lg ${x.err?'bg-red-700':'bg-ink'}`}>{x.m}</div>)}</div>}
export function Modal({open,onClose,label,children,wide}){useEffect(()=>{if(!open)return;const k=e=>e.key==='Escape'&&onClose();addEventListener('keydown',k);document.body.style.overflow='hidden';return()=>{removeEventListener('keydown',k);document.body.style.overflow=''}},[open]);
 return<AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true" aria-label={label} className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/50 p-5" onClick={onClose}><motion.div initial={{scale:.96}} animate={{scale:1}} className={`w-full ${wide?'max-w-2xl':'max-w-md'} rounded-2xl bg-white p-6`} onClick={e=>e.stopPropagation()}>{children}</motion.div></motion.div>}</AnimatePresence>}
export const Confirm=({open,onYes,onNo})=><Modal open={open} onClose={onNo} label="Confirm delete"><h2 className="text-xl">Are you sure?</h2><p className="mt-1 text-sm text-mute">This cannot be undone.</p><div className="mt-5 flex gap-3"><button autoFocus onClick={onNo} className={Ghost}>Cancel</button><button onClick={onYes} className={Primary}>Delete</button></div></Modal>;
export function Stat({to,dec=0,suffix='',label}){const[v,setV]=useState(0),ref=useRef();
 useEffect(()=>{const o=new IntersectionObserver(([e])=>{if(!e.isIntersecting)return;o.disconnect();const t0=performance.now(),f=t=>{const p=Math.min((t-t0)/1200,1);setV(to*p);p<1&&requestAnimationFrame(f)};requestAnimationFrame(f)});o.observe(ref.current);return()=>o.disconnect()},[]);
 return<div ref={ref} className="text-center"><p className="font-serif text-4xl text-rose">{v.toFixed(dec)}{suffix}</p><p className="mt-1 text-sm text-mute">{label}</p></div>}
export function DatePicker({value,onChange}){const iso=d=>d.toLocaleDateString('en-CA',{timeZone:'Africa/Lagos'}),today=iso(new Date());
 const[m,setM]=useState(()=>{const d=new Date((value||today)+'T12:00:00Z');return{y:d.getUTCFullYear(),mo:d.getUTCMonth()}});
 const first=new Date(Date.UTC(m.y,m.mo,1)).getUTCDay(),days=new Date(Date.UTC(m.y,m.mo+1,0)).getUTCDate(),cells=[...Array(first).fill(null),...Array.from({length:days},(_,i)=>i+1)];
 const ym=`${m.y}-${String(m.mo+1).padStart(2,'0')}`,go=n=>setM(x=>{const d=new Date(Date.UTC(x.y,x.mo+n,1));return{y:d.getUTCFullYear(),mo:d.getUTCMonth()}});
 return<div className="max-w-sm rounded-2xl border border-line bg-white p-4"><div className="flex items-center justify-between"><button type="button" aria-label="Previous month" disabled={ym<=today.slice(0,7)} onClick={()=>go(-1)} className="px-3 py-1 text-xl disabled:opacity-30">‹</button><b>{new Date(Date.UTC(m.y,m.mo,1)).toLocaleDateString('en-GB',{month:'long',year:'numeric',timeZone:'UTC'})}</b><button type="button" aria-label="Next month" onClick={()=>go(1)} className="px-3 py-1 text-xl">›</button></div>
 <div className="mt-3 grid grid-cols-7 gap-1 text-center">{'SMTWTFS'.split('').map((d,i)=><span key={i} className="text-xs text-mute">{d}</span>)}
 {cells.map((d,i)=>{if(!d)return<span key={i}/>;const k=`${ym}-${String(d).padStart(2,'0')}`,off=k<today||new Date(k+'T12:00:00Z').getUTCDay()===0;
 return<button type="button" key={i} disabled={off} aria-pressed={value===k} aria-label={k} onClick={()=>onChange(k)} className={`aspect-square rounded-full text-sm ${value===k?'bg-rose text-white':'hover:bg-blush/30'} disabled:pointer-events-none disabled:text-line`}>{d}</button>})}</div></div>}
