import{Link}from'react-router-dom';import{Search,CalendarDays,Sparkles,Heart,ShieldCheck,Home,Smile}from'lucide-react';import{useSeo}from'../hooks.js';import{Primary}from'../App.jsx';import{Img,Stat}from'../ui.jsx';
const vals=[['Quality','Every set receives careful attention to detail.'],['Creativity','Your nails should feel personal to you.'],['Comfort','Appointments should feel relaxed and welcoming.'],['Cleanliness','Tools and workspace should be maintained carefully.']];
const why=[[Heart,'Personalized','Every appointment is tailored to your style.'],[ShieldCheck,'Quality Products','Professional products selected for quality and finish.'],[Home,'Clean Studio','A comfortable, tidy and welcoming environment.'],[Smile,'Friendly Experience','Friendly service from booking to final result.']];
const steps=[[Search,'01','Choose Your Set','Browse services and find a style you love.'],[CalendarDays,'02','Book Your Time','Choose a date and available appointment time.'],[Sparkles,'03','Get Your Glow','Show up, relax and leave with a fresh set.']];
export default function About(){useSeo('About Mia | NailsByMia','Meet Mia Williams, the nail artist behind NailsByMia in Ikeja, Lagos.');
 return<><section className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-14 md:grid-cols-2"><div><p className="text-xs tracking-[.3em] text-rose">MEET MIA</p><h1 className="mt-3 text-4xl sm:text-5xl">More than just nails.</h1>
 <p className="mt-5 text-mute">Hi, I'm Mia, the nail artist behind NailsByMia. I love creating clean, detailed and beautiful nail sets that help my clients feel confident and express their personal style.</p>
 <p className="mt-3 text-mute">What started as a passion for nail art became a studio in Ikeja, Lagos, where every set is designed around the person wearing it, from everyday looks to events and special occasions.</p><Link to="/book" className={Primary+' mt-6'}>Book with Mia</Link></div>
 <Img src="https://picsum.photos/seed/nbmmia/800/900" alt="Mia Williams, nail artist at NailsByMia" className="aspect-[4/5] w-full rounded-[2rem] object-cover"/></section>
 <section className="mx-auto grid max-w-3xl grid-cols-2 gap-6 px-5"><Stat to={3} suffix="+" label="Years experience"/><Stat to={500} suffix="+" label="Happy clients"/></section>
 <section className="mx-auto mt-20 max-w-6xl px-5"><h2 className="text-3xl">What we value</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{vals.map(([t,d])=><div key={t} className="rounded-2xl border border-line bg-white p-6"><h3 className="text-xl">{t}</h3><p className="mt-2 text-sm text-mute">{d}</p></div>)}</div></section>
 <section className="mx-auto mt-20 max-w-6xl px-5"><h2 className="text-3xl">Why choose NailsByMia</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{why.map(([I,t,d])=><div key={t} className="rounded-2xl bg-blush/20 p-6"><I className="text-rose"/><h3 className="mt-3 text-xl">{t}</h3><p className="mt-2 text-sm text-mute">{d}</p></div>)}</div></section>
 <section className="mx-auto mt-20 max-w-6xl px-5"><h2 className="text-3xl">How it works</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{steps.map(([I,n,t,d])=><div key={n} className="rounded-2xl border border-line bg-white p-6"><I className="text-rose"/><p className="mt-3 text-xs tracking-widest text-rose">{n}</p><h3 className="text-xl">{t}</h3><p className="mt-1 text-sm text-mute">{d}</p></div>)}</div></section></>}
