import{useState,useEffect}from'react';import{NavLink,Navigate,Route,Routes,useNavigate}from'react-router-dom';
import{api,naira}from'../api.js';import{Primary,Ghost}from'../App.jsx';import{Err,Img,Modal,Confirm,toast}from'../ui.jsx';import{Dashboard}from'./Admin.jsx';
const I='mt-1 w-full rounded-xl border border-line px-4 py-2';
function Manager({title,plural,path,fields=[],cols,blank={},noAdd,noEdit,empty}){
 const[rows,setRows]=useState(null),[err,setErr]=useState(''),[edit,setEdit]=useState(null),[del,setDel]=useState(null),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[pg,setPg]=useState(1);
 const load=()=>api(path).then(setRows).catch(e=>setErr(e.message));useEffect(()=>{load()},[]);
 const set=(f,v)=>setEdit({...edit,[f.k]:f.t==='number'&&v!==''?Number(v):v});
 const save=async e=>{e.preventDefault();setBusy(true);try{const{_id,__v,createdAt,updatedAt,...b}=edit;await api(_id?`${path}/${_id}`:path,{method:_id?'PUT':'POST',body:b});toast(`${title} ${_id?'updated':'created'}`);setEdit(null);load()}catch(x){toast(x.message,1)}setBusy(false)};
 const remove=async()=>{try{await api(`${path}/${del}`,{method:'DELETE'});toast(`${title} deleted`)}catch(x){toast(x.message,1)}setDel(null);load()};
 const toggle=async(r,k)=>{try{await api(`${path}/${r._id}`,{method:'PUT',body:{[k]:!r[k]}});toast(`${title} updated`);load()}catch(x){toast(x.message,1)}};
 const list=(rows||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),pages=Math.max(1,Math.ceil(list.length/10)),view=list.slice((pg-1)*10,pg*10),ctx={toggle,reload:load};
 return<div className="mx-auto max-w-6xl px-5 py-8"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl">{plural}</h1>{!noAdd&&<button onClick={()=>setEdit(blank)} className={Primary}>Add {title}</button>}</div>
 <input aria-label={`Search ${plural}`} placeholder="Search" value={q} onChange={e=>{setQ(e.target.value);setPg(1)}} className="mt-4 rounded-xl border border-line px-4 py-2"/>
 {err?<div className="mt-4"><Err msg={err} retry={load}/></div>:!rows?<p className="mt-6 text-mute">Loading...</p>:list.length===0?<p className="mt-6 text-mute">{empty}</p>:
 <><div className="mt-4 overflow-x-auto rounded-2xl border border-line bg-white"><table className="w-full text-left text-sm"><thead className="text-xs text-mute"><tr>{cols.map(c=><th key={c[0]} className="p-3">{c[0]}</th>)}<th className="p-3">Actions</th></tr></thead><tbody>
 {view.map(r=><tr key={r._id} className="border-t border-line align-top">{cols.map(c=><td key={c[0]} className="p-3">{c[1](r,ctx)}</td>)}<td className="p-3"><div className="flex gap-3 text-xs">{!noEdit&&<button className="underline" onClick={()=>setEdit(r)}>Edit</button>}<button className="text-red-700 underline" onClick={()=>setDel(r._id)}>Delete</button></div></td></tr>)}</tbody></table></div>
 <div className="mt-4 flex items-center gap-3 text-sm"><button disabled={pg<=1} onClick={()=>setPg(pg-1)} className={Ghost}>Previous</button>Page {pg} of {pages}<button disabled={pg>=pages} onClick={()=>setPg(pg+1)} className={Ghost}>Next</button></div></>}
 <Modal open={!!edit} onClose={()=>setEdit(null)} label={title} wide>{edit&&<form onSubmit={save} className="grid gap-3 sm:grid-cols-2"><h2 className="text-2xl sm:col-span-2">{edit._id?'Edit':'Add'} {title}</h2>
 {fields.map(f=><label key={f.k} className={`text-sm font-medium ${f.t==='textarea'?'sm:col-span-2':''} ${f.t==='checkbox'?'flex items-center gap-2':''}`}>
 {f.t==='checkbox'?<><input type="checkbox" checked={!!edit[f.k]} onChange={e=>set(f,e.target.checked)}/>{f.l}</>:<>{f.l}
 {f.t==='select'?<select className={I} value={edit[f.k]||''} onChange={e=>set(f,e.target.value)}>{f.o.map(o=><option key={o}>{o}</option>)}</select>:f.t==='textarea'?<textarea rows="3" required={f.req} className={I} value={edit[f.k]||''} onChange={e=>set(f,e.target.value)}/>:<input type={f.t||'text'} required={f.req} min={f.min} max={f.max} className={I} value={edit[f.k]??''} onChange={e=>set(f,e.target.value)}/>}</>}</label>)}
 {(edit.image||edit.avatar)&&<Img src={edit.image||edit.avatar} alt="Preview" className="h-24 w-24 rounded-xl object-cover"/>}
 <div className="flex gap-3 sm:col-span-2"><button type="button" onClick={()=>setEdit(null)} className={Ghost}>Cancel</button><button disabled={busy} className={Primary}>{busy?'Saving...':'Save'}</button></div></form>}</Modal>
 <Confirm open={!!del} onYes={remove} onNo={()=>setDel(null)}/></div>}
const Tog=(r,ctx,k,a,b)=><button onClick={()=>ctx.toggle(r,k)} className={`rounded-full px-3 py-1 text-xs ${r[k]?'bg-green-100 text-green-800':'bg-line text-mute'}`}>{r[k]?a:b}</button>;
const Services=()=><Manager title="Service" plural="Services" path="/services" empty="No services yet." blank={{category:'Gel',active:true,price:0,duration:60}}
 fields={[{k:'name',l:'Name',req:1},{k:'category',l:'Category',t:'select',o:['Gel','Acrylic','Extensions','Nail Art','Removal']},{k:'price',l:'Price (₦)',t:'number',min:0,req:1},{k:'priceLabel',l:'Price label (optional)'},{k:'duration',l:'Duration (minutes)',t:'number',min:5,req:1},{k:'image',l:'Image URL'},{k:'description',l:'Description',t:'textarea'},{k:'active',l:'Active',t:'checkbox'},{k:'featured',l:'Featured on home',t:'checkbox'}]}
 cols={[['Name',r=>r.name],['Category',r=>r.category],['Price',r=>r.priceLabel||naira(r.price)],['Duration',r=>r.duration+' min'],['Status',(r,c)=>Tog(r,c,'active','Active','Inactive')]]}/>;
const Gallery=()=><Manager title="Design" plural="Gallery" path="/gallery" empty="No designs found." blank={{category:'French'}}
 fields={[{k:'title',l:'Title',req:1},{k:'category',l:'Category',t:'select',o:['French','Chrome','Acrylic','Simple','Custom']},{k:'image',l:'Image URL',req:1},{k:'description',l:'Description',t:'textarea'}]}
 cols={[['Image',r=><Img src={r.image} alt={r.title} className="h-12 w-12 rounded-lg object-cover"/>],['Title',r=>r.title],['Category',r=>r.category]]}/>;
const Testimonials=()=><Manager title="Testimonial" plural="Testimonials" path="/testimonials" empty="No testimonials have been added yet." blank={{rating:5,approved:true}}
 fields={[{k:'customerName',l:'Customer name',req:1},{k:'rating',l:'Rating (1-5)',t:'number',min:1,max:5,req:1},{k:'review',l:'Review',t:'textarea',req:1},{k:'avatar',l:'Avatar URL'},{k:'approved',l:'Approved (shown publicly)',t:'checkbox'}]}
 cols={[['Customer',r=>r.customerName],['Rating',r=>'★'.repeat(r.rating)],['Review',r=><span className="block max-w-xs">{r.review}</span>],['Public',(r,c)=>Tog(r,c,'approved','Approved','Approve')]]}/>;
const Messages=()=><Manager title="Message" plural="Messages" path="/contact" empty="Your inbox is empty." noAdd noEdit
 cols={[['Name',r=>r.name],['Email',r=>r.email],['Phone',r=>r.phone||'—'],['Subject',r=>r.subject||'—'],['Message',r=><span className="block max-w-xs whitespace-pre-wrap">{r.message}</span>],['Date',r=>new Date(r.createdAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})],
 ['Status',(r,c)=><select aria-label="Message status" value={r.status} className="rounded-lg border border-line p-1" onChange={async e=>{try{await api('/contact/'+r._id,{method:'PUT',body:{status:e.target.value}});toast('Message updated');c.reload()}catch(x){toast(x.message,1)}}}><option value="new">New (unread)</option><option value="read">Read</option><option value="replied">Replied</option></select>]]}/>;
const SF=['businessName','tagline','phone','email','whatsapp','instagram','tiktok','location'];
function Settings(){const[s,setS]=useState(null),[hours,setHours]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/settings').then(d=>{setS(d||{});setHours(Object.entries(d?.hours||{}).map(([k,v])=>`${k}: ${v}`).join('\n'))}).catch(e=>toast(e.message,1))},[]);
 const save=async e=>{e.preventDefault();setBusy(true);try{const h=Object.fromEntries(hours.split('\n').filter(l=>l.includes(':')).map(l=>{const i=l.indexOf(':');return[l.slice(0,i).trim(),l.slice(i+1).trim()]}));const{_id,__v,createdAt,updatedAt,...b}=s;await api('/settings',{method:'PUT',body:{...b,hours:h}});toast('Settings saved')}catch(x){toast(x.message,1)}setBusy(false)};
 if(!s)return<p className="p-8 text-mute">Loading...</p>;
 return<form onSubmit={save} className="mx-auto max-w-2xl px-5 py-8"><h1 className="text-3xl">Settings</h1><div className="mt-6 grid gap-4 sm:grid-cols-2">{SF.map(k=><label key={k} className="text-sm font-medium capitalize">{k.replace(/([A-Z])/g,' $1')}<input className={I} value={s[k]||''} onChange={e=>setS({...s,[k]:e.target.value})}/></label>)}
 <label className="text-sm font-medium sm:col-span-2">Opening hours (one per line, "Day: hours")<textarea rows="5" className={I} value={hours} onChange={e=>setHours(e.target.value)}/></label></div><button disabled={busy} className={Primary+' mt-6'}>{busy?'Saving...':'Save Settings'}</button></form>}
const links=[['dashboard','Dashboard'],['appointments','Appointments'],['services','Services'],['gallery','Gallery'],['testimonials','Testimonials'],['messages','Messages'],['settings','Settings']];
export function Shell(){const nav=useNavigate();if(!localStorage.getItem('nbm_token'))return<Navigate to="/admin/login" replace/>;
 const logout=async()=>{await api('/auth/logout',{method:'POST'}).catch(()=>{});localStorage.removeItem('nbm_token');nav('/admin/login')};
 return<div className="md:flex"><nav aria-label="Admin" className="flex gap-1 overflow-x-auto border-b border-line bg-white p-3 md:min-h-screen md:w-56 md:shrink-0 md:flex-col md:border-b-0 md:border-r"><p className="hidden px-3 py-2 font-serif text-xl md:block">NailsByMia</p>
 {links.map(([p,l])=><NavLink key={p} to={'/admin/'+p} className={({isActive})=>`shrink-0 rounded-xl px-3 py-2 text-sm ${isActive?'bg-blush/30 text-rose':'text-mute hover:text-ink'}`}>{l}</NavLink>)}
 <button onClick={logout} className="shrink-0 rounded-xl px-3 py-2 text-left text-sm text-red-700">Logout</button></nav>
 <div className="min-w-0 flex-1"><Routes><Route path="dashboard" element={<Dashboard/>}/><Route path="appointments" element={<Dashboard/>}/><Route path="services" element={<Services/>}/><Route path="gallery" element={<Gallery/>}/><Route path="testimonials" element={<Testimonials/>}/><Route path="messages" element={<Messages/>}/><Route path="settings" element={<Settings/>}/><Route path="*" element={<Navigate to="dashboard" replace/>}/></Routes></div></div>}
