import{useState,useEffect}from'react';import{Navigate,useNavigate}from'react-router-dom';import{Eye,EyeOff}from'lucide-react';import{api,naira,ORIGIN}from'../api.js';import{Primary,Ghost}from'../App.jsx';import{Err}from'../ui.jsx';
export function AdminLogin(){const[e,setE]=useState(''),[p,setP]=useState(''),[show,setShow]=useState(false),[err,setErr]=useState(''),[busy,setBusy]=useState(false),nav=useNavigate();
 const go=async ev=>{ev.preventDefault();setBusy(true);setErr('');try{const r=await api('/auth/login',{method:'POST',body:{email:e,password:p}});localStorage.setItem('nbm_token',r.token);nav('/admin/dashboard')}catch(x){setErr(x.message)}setBusy(false)};
 return<div className="grid min-h-screen place-items-center px-5"><form onSubmit={go} className="w-full max-w-sm rounded-2xl border border-line bg-white p-8"><h1 className="text-3xl">Admin Sign In</h1>
 <label className="mt-6 block text-sm font-medium">Email<input type="email" required value={e} onChange={x=>setE(x.target.value)} className="mt-1 w-full rounded-xl border border-line px-4 py-3"/></label>
 <label className="mt-4 block text-sm font-medium">Password<span className="relative block"><input type={show?'text':'password'} required value={p} onChange={x=>setP(x.target.value)} className="mt-1 w-full rounded-xl border border-line px-4 py-3"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)} className="absolute right-3 top-4">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>
 {err&&<p role="alert" className="mt-3 text-sm text-red-700">{err}</p>}<button disabled={busy} className={Primary+' mt-6 w-full'}>{busy?'Signing in...':'Sign In'}</button></form></div>}
const col={pending:'bg-amber-100 text-amber-800',confirmed:'bg-blue-100 text-blue-800',completed:'bg-green-100 text-green-800',cancelled:'bg-red-100 text-red-800'};
export function Dashboard(){const nav=useNavigate(),[rows,setRows]=useState(null),[err,setErr]=useState(''),[q,setQ]=useState(''),[fs,setFs]=useState(''),[fd,setFd]=useState(''),[fv,setFv]=useState(''),[pg,setPg]=useState(1),[sel,setSel]=useState(null),[del,setDel]=useState(null),[stat,setStat]=useState({});
 const load=()=>Promise.all([api('/appointments'),api('/contact'),api('/services')]).then(([a,m,s])=>{setRows(a);setStat({msgs:m.length,svcs:s.length})}).catch(x=>x.status!==401&&setErr(x.message));
 useEffect(()=>{load()},[]);
 if(!localStorage.getItem('nbm_token'))return<Navigate to="/admin/login" replace/>;
 const act=async(id,status)=>{await api('/appointments/'+id,{method:'PUT',body:{status}});setSel(null);load()};
 const remove=async()=>{await api('/appointments/'+del,{method:'DELETE'});setDel(null);setSel(null);load()};
 const logout=async()=>{await api('/auth/logout',{method:'POST'}).catch(()=>{});localStorage.removeItem('nbm_token');nav('/admin/login')};
 const list=(rows||[]).filter(a=>(!fs||a.status===fs)&&(!fd||a.date===fd)&&(!fv||a.service===fv)&&(`${a.customerName} ${a.phone} ${a.bookingId}`.toLowerCase().includes(q.toLowerCase())));
 const pages=Math.max(1,Math.ceil(list.length/10)),view=list.slice((pg-1)*10,pg*10),n=s=>(rows||[]).filter(a=>a.status===s).length;
 return<div className="mx-auto max-w-6xl px-5 py-8"><div className="flex items-center justify-between"><h1 className="text-3xl">NailsByMia Dashboard</h1></div>
 {err?<Err msg={err} retry={load}/>:!rows?<p className="mt-8 text-mute">Loading...</p>:<>
 <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-6">{[['Total',rows.length],['Pending',n('pending')],['Confirmed',n('confirmed')],['Completed',n('completed')],['Messages',stat.msgs],['Services',stat.svcs]].map(([k,v])=><div key={k} className="rounded-2xl border border-line bg-white p-4"><p className="text-xs text-mute">{k}</p><p className="text-2xl font-semibold">{v}</p></div>)}</div>
 <div className="mt-8 flex flex-wrap gap-3"><input aria-label="Search" placeholder="Search name, phone, booking ID" value={q} onChange={e=>{setQ(e.target.value);setPg(1)}} className="rounded-xl border border-line px-4 py-2"/>
  <select aria-label="Status" value={fs} onChange={e=>{setFs(e.target.value);setPg(1)}} className="rounded-xl border border-line px-4 py-2"><option value="">All statuses</option>{Object.keys(col).map(s=><option key={s}>{s}</option>)}</select><input type="date" aria-label="Date" value={fd} onChange={e=>{setFd(e.target.value);setPg(1)}} className="rounded-xl border border-line px-4 py-2"/><select aria-label="Service" value={fv} onChange={e=>{setFv(e.target.value);setPg(1)}} className="rounded-xl border border-line px-4 py-2"><option value="">All services</option>{[...new Set((rows||[]).map(a=>a.service))].map(s=><option key={s}>{s}</option>)}</select></div>
 {list.length===0?<p className="mt-6 text-mute">No appointments yet.</p>:<div className="mt-4 overflow-x-auto rounded-2xl border border-line bg-white"><table className="w-full text-left text-sm"><thead className="text-xs text-mute"><tr>{['Booking ID','Customer','Service','Date','Time','Phone','Status','Actions'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>
 {view.map(a=><tr key={a._id} className="border-t border-line"><td className="p-3">{a.bookingId}</td><td className="p-3">{a.customerName}</td><td className="p-3">{a.service}</td><td className="p-3 whitespace-nowrap">{a.date}</td><td className="p-3 whitespace-nowrap">{a.time}</td><td className="p-3">{a.phone}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs ${col[a.status]}`}>{a.status}</span></td>
 <td className="p-3"><div className="flex flex-wrap gap-2 text-xs"><button className="underline" onClick={()=>setSel(a)}>View</button>{a.status==='pending'&&<button className="underline" onClick={()=>act(a._id,'confirmed')}>Confirm</button>}{['pending','confirmed'].includes(a.status)&&<><button className="underline" onClick={()=>act(a._id,'completed')}>Complete</button><button className="underline" onClick={()=>act(a._id,'cancelled')}>Cancel</button></>}<button className="text-red-700 underline" onClick={()=>setDel(a._id)}>Delete</button></div></td></tr>)}</tbody></table></div>}
 <div className="mt-4 flex items-center gap-3 text-sm"><button disabled={pg<=1} onClick={()=>setPg(pg-1)} className={Ghost}>Previous</button>Page {pg} of {pages}<button disabled={pg>=pages} onClick={()=>setPg(pg+1)} className={Ghost}>Next</button></div></>}
 {sel&&<div role="dialog" aria-modal="true" aria-label="Appointment details" className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-5" onClick={()=>setSel(null)} onKeyDown={e=>e.key==='Escape'&&setSel(null)}><div className="w-full max-w-md rounded-2xl bg-white p-6 text-sm" onClick={e=>e.stopPropagation()}><h2 className="text-2xl">{sel.bookingId}</h2>
  {[['Customer',sel.customerName],['Phone',sel.phone],['Email',sel.email||'—'],['Service',sel.service],['Price',naira(sel.price)],['Duration',sel.duration+' min'],['When',`${sel.date}, ${sel.time}`],['Notes',sel.notes||'—'],['Created',new Date(sel.createdAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})]].map(([k,v])=><p key={k} className="mt-2"><span className="text-mute">{k}: </span>{v}</p>)}
  {sel.referenceImage&&<img src={ORIGIN+sel.referenceImage} alt="Customer reference" className="mt-3 h-32 rounded-xl object-cover"/>}<button autoFocus onClick={()=>setSel(null)} className={Ghost+' mt-5'}>Close</button></div></div>}
 {del&&<div role="alertdialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-5"><div className="rounded-2xl bg-white p-6"><h2 className="text-xl">Are you sure?</h2><p className="mt-1 text-sm text-mute">This appointment will be permanently deleted.</p><div className="mt-5 flex gap-3"><button autoFocus onClick={()=>setDel(null)} className={Ghost}>Cancel</button><button onClick={remove} className={Primary}>Delete</button></div></div></div>}</div>}
