import{useState,useEffect}from'react';import{useSearchParams,Link}from'react-router-dom';import{api,naira,wa,longDate}from'../api.js';import{useApi,useSeo}from'../hooks.js';import{Primary,Ghost}from'../App.jsx';import{Err,Skel,DatePicker}from'../ui.jsx';
const F='mt-1 w-full rounded-xl border border-line bg-white px-4 py-3';
const iso=d=>d.toLocaleDateString('en-CA',{timeZone:'Africa/Lagos'});
export default function Book(){useSeo('Book an Appointment | NailsByMia','Choose your nail service, date and time with NailsByMia in Ikeja, Lagos.');
 const[sp]=useSearchParams(),sv=useApi('/services'),[step,setStep]=useState(1),[svc,setSvc]=useState(null),[date,setDate]=useState(''),[time,setTime]=useState('');
 const[slots,setSlots]=useState(null),[slotErr,setSlotErr]=useState(''),[f,setF]=useState({customerName:'',phone:'',email:'',notes:''}),[file,setFile]=useState(null),[errs,setErrs]=useState({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[done,setDone]=useState(null);
 useEffect(()=>{const id=sp.get('service');if(id&&sv.data){const s=sv.data.find(x=>x._id===id);if(s){setSvc(s);setStep(2)}}},[sv.data]);
 useEffect(()=>{if(!date)return;setSlots(null);setSlotErr('');setTime('');api('/appointments/availability?date='+date).then(setSlots).catch(e=>setSlotErr(e.message))},[date]);
 const today=iso(new Date()),sunday=date&&new Date(date+'T12:00:00Z').getUTCDay()===0;
 const validate=()=>{const e={};if(!f.customerName.trim())e.customerName='Full name is required.';if(!/^\+?[\d\s-]{7,15}$/.test(f.phone))e.phone='Phone number is required.';if(f.email&&!/^\S+@\S+\.\S+$/.test(f.email))e.email='Email is not valid.';setErrs(e);return!Object.keys(e).length};
 const pick=e=>{const x=e.target.files[0];if(!x)return setFile(null);if(!['image/jpeg','image/png','image/webp'].includes(x.type)||x.size>3e6){setErrs({...errs,file:'Use a JPG, PNG or WEBP image under 3MB.'});return}setErrs({...errs,file:''});setFile(x)};
 const submit=async()=>{if(busy)return;setBusy(true);setMsg('');const fd=new FormData();Object.entries({...f,serviceId:svc._id,date,time}).forEach(([k,v])=>v&&fd.append(k,v));if(file)fd.append('referenceImage',file);
  try{setDone(await api('/appointments',{method:'POST',form:fd}))}catch(e){if(e.status===409){setMsg(e.message);setStep(3);setTime('');api('/appointments/availability?date='+date).then(setSlots)}else setMsg(e.status?e.message:"We couldn't complete your booking. Please try again.")}setBusy(false)};
 if(done)return<section className="mx-auto max-w-xl px-5 py-16 text-center"><h1 className="text-4xl">Appointment Request Received 💅</h1><p className="mt-3 text-mute">Thank you for booking with NailsByMia. Your appointment request has been received.</p>
  <dl className="mt-8 grid gap-2 rounded-2xl border border-line bg-white p-6 text-left text-sm">{[['Booking ID',done.bookingId],['Name',done.customerName],['Service',done.service],['Date',longDate(done.date)],['Time',done.time],['Price',naira(done.price)],['Status','Pending']].map(([k,v])=><div key={k} className="flex justify-between"><dt className="text-mute">{k}</dt><dd className="font-semibold">{v}</dd></div>)}</dl>
  <div className="mt-6 flex justify-center gap-3"><a target="_blank" rel="noopener noreferrer" className={Primary} href={wa(`Hi NailsByMia! I'd like to book an appointment.\n\nName: ${done.customerName}\nService: ${done.service}\nDate: ${longDate(done.date)}\nTime: ${done.time}\n\nBooking ID: ${done.bookingId}`)}>Chat on WhatsApp</a><Link to="/" className={Ghost}>Back Home</Link></div></section>;
 const Nav=({back,next,label='Continue',off})=><div className="mt-8 flex gap-3">{back&&<button onClick={()=>setStep(back)} className={Ghost}>Back</button>}<button disabled={off||busy} onClick={next} className={Primary}>{label}</button></div>;
 return<section className="mx-auto max-w-3xl px-5 py-14"><h1 className="text-4xl sm:text-5xl">Book your appointment</h1><p className="mt-2 text-mute">Choose your service and preferred time. We'll take care of the rest.</p>
 <p className="mt-6 text-xs tracking-widest text-rose">STEP {step} OF 5</p>
 {msg&&<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{msg}</p>}
 {step===1&&<div className="mt-4">{sv.loading?<Skel n={2}/>:sv.error?<Err msg="We couldn't load our services right now." retry={sv.reload}/>:<div className="grid gap-3 sm:grid-cols-2">{sv.data.map(s=><button key={s._id} aria-pressed={svc?._id===s._id} onClick={()=>setSvc(s)} className={`rounded-2xl border p-4 text-left ${svc?._id===s._id?'border-rose bg-blush/20 ring-2 ring-rose':'border-line bg-white'}`}><b>{s.name}</b><span className="block text-sm text-mute">{s.priceLabel||naira(s.price)} · {s.duration} min</span></button>)}</div>}<Nav off={!svc} next={()=>setStep(2)}/></div>}
 {step===2&&<div className="mt-4"><DatePicker value={date} onChange={setDate}/>{sunday&&<p className="mt-2 text-sm text-red-700">We are closed on Sundays.</p>}<Nav back={1} off={!date||sunday} next={()=>setStep(3)}/></div>}
 {step===3&&<div className="mt-4"><p className="text-sm text-mute">{longDate(date)}</p>{slotErr?<Err msg={slotErr}/>:!slots?<Skel n={3}/>:<div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{slots.map(s=><button key={s.time} disabled={!s.available} aria-pressed={time===s.time} onClick={()=>setTime(s.time)} className={`rounded-xl border px-3 py-3 text-sm ${time===s.time?'border-rose bg-rose text-white':'border-line bg-white'} disabled:bg-line disabled:text-mute disabled:line-through`}>{s.time}{!s.available&&<span className="block text-[10px] no-underline">Unavailable</span>}</button>)}</div>}<Nav back={2} off={!time} next={()=>setStep(4)}/></div>}
 {step===4&&<div className="mt-4 grid gap-4">{[['customerName','Full Name *'],['phone','Phone Number *'],['email','Email (optional)']].map(([k,l])=><label key={k} className="text-sm font-medium">{l}<input className={F} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>{errs[k]&&<span role="alert" className="text-xs text-red-700">{errs[k]}</span>}</label>)}
  <label className="text-sm font-medium">Additional Notes<textarea rows="3" className={F} value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label>
  <label className="text-sm font-medium">Reference image (JPG, PNG, WEBP, max 3MB)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={pick} className="mt-1 block text-sm"/>{errs.file&&<span role="alert" className="text-xs text-red-700">{errs.file}</span>}</label>
  {file&&<img src={URL.createObjectURL(file)} alt="Your reference preview" className="h-32 w-32 rounded-xl object-cover"/>}<Nav back={3} next={()=>validate()&&setStep(5)}/></div>}
 {step===5&&<div className="mt-4"><dl className="grid gap-2 rounded-2xl border border-line bg-white p-6 text-sm">{[['Service',svc.name],['Price',svc.priceLabel||naira(svc.price)],['Duration',svc.duration+' min'],['Date',longDate(date)],['Time',time],['Name',f.customerName],['Phone',f.phone],['Email',f.email||'—'],['Notes',f.notes||'—'],['Reference',file?file.name:'—']].map(([k,v])=><div key={k} className="flex justify-between gap-4"><dt className="text-mute">{k}</dt><dd className="text-right font-semibold">{v}</dd></div>)}</dl>
  <div className="mt-6 flex gap-3"><button onClick={()=>setStep(4)} className={Ghost}>Edit</button><button disabled={busy} onClick={submit} className={Primary}>{busy?'Booking your appointment...':'Confirm Appointment'}</button></div></div>}</section>}
